Repository fluxendd/fluxend, pull requests merged in 2025-05, with the labels that each got.

#54 [Feature] Support Sendgrid and Mailgun email providers
  constants/general.go
  database/seeders/seed_settings.go
  go.mod
  go.sum
  services/backup_workflow_service.go
  services/container_service.go
  services/email/interface.go
  services/email/mailgun_service.go
  services/email/provider.go
  services/email/sendgrid_service.go
  services/email/ses_service.go
  services/file_service.go
  services/storage/backblze_service.go
  services/storage/dropbox_service.go
  services/storage/interface.go
  services/storage/provider.go
  services/storage/s3_service.go
Labels: feature

#55 [Feature] Support CSV Imports to Collection with Endpoints
  cmd/container.go
  constants/column.go
  controllers/table_controller.go
  go.mod
  go.sum
  message/message.go
  repositories/column_repository.go
  repositories/row_repository.go
  requests/base_request.go
  requests/table_requests/upload_request.go
  routes/table_routes.go
  services/connection_service.go
  services/file_import_service.go
  services/file_import_service_test.go
  services/table_service.go
Labels: feature

#57 [Fix] Allow multiple login sessions
  internal/api/middlewares/auth_middleware.go
  internal/config/constants/user.go
Labels: bug

#61 [FLX-56] Cleaner response mappers
  Makefile
  internal/api/handlers/backup.go
  internal/api/handlers/column.go
  internal/api/handlers/container.go
  internal/api/handlers/file.go
  internal/api/handlers/form.go
  internal/api/handlers/form_field.go
  internal/api/handlers/form_response.go
  internal/api/handlers/function.go
  internal/api/handlers/log.go
  internal/api/handlers/organization.go
  internal/api/handlers/organization_member.go
  internal/api/handlers/project.go
  internal/api/handlers/setting.go
  internal/api/handlers/table.go
  internal/api/handlers/user.go
  internal/api/mapper/backup.go
  internal/api/mapper/column.go
  internal/api/mapper/container.go
  internal/api/mapper/file.go
  internal/api/mapper/form.go
  internal/api/mapper/function.go
  internal/api/mapper/log.go
  internal/api/mapper/organization.go
  internal/api/mapper/project.go
  internal/api/mapper/setting.go
  internal/api/mapper/table.go
  internal/api/mapper/user.go
Labels: enhancement

#67 [FLX-16] Support log search
  Dockerfile
  README.md
  docs/docs.go
  docs/swagger.json
  docs/swagger.yaml
  internal/api/dto/logging/mapper.go
  internal/api/dto/logging/requests.go
  internal/api/handlers/log.go
  internal/database/repositories/container.go
  internal/database/repositories/request_log.go
  internal/domain/logging/repository.go
  internal/domain/logging/service.go
  internal/domain/logging/types.go
Labels: enhancement
